name: Continous integration for Tomatenquark
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build for OSX
        working-directory: ./src/xcode
        run: xcodebuild
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build for Windows
        working-directory: ./src/vcpp
        run: msbuild /p:PlatformToolset=v142 /property:Platform=x64 tomatenquark.sln
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install C and C++ header files
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl-dev libsdl2-mixer-dev libsdl2-image-dev zlib1g-dev libcurl4-openssl-dev
      - name: Build for Ubuntu
        working-directory: ./src
        run: make
